/**
 * Core payment related types used across the payment infrastructure.
 */
export type ParticipantType = 'human' | 'agent';

export interface PaymentRequest {
  /** Unique identifier for the payment request */
  id: string;
  /** Sender participant type */
  fromType: ParticipantType;
  /** Receiver participant type */
  toType: ParticipantType;
  /** Sender identifier (e.g., wallet address) */
  from: string;
  /** Receiver identifier */
  to: string;
  /** Amount in minor units (e.g., cents) */
  amount: number;
  /** Asset symbol, default USDC */
  asset: string;
  /** Optional memo or description */
  memo?: string;
  /** Optional tags for routing (e.g., 'arc', 'payx', 'streampay') */
  tags?: string[];
}

export interface PaymentResponse {
  /** Payment identifier generated by the system */
  paymentId: string;
  /** Final state of the payment */
  status: 'pending' | 'completed' | 'failed';
  /** Any error message if failed */
  error?: string;
  /** Fees applied */
  fee?: FeeInfo;
}

export interface FeeInfo {
  /** Fee amount in minor units */
  amount: number;
  /** Asset for the fee */
  asset: string;
  /** Description of fee source (e.g., 'circle', 'arc') */
  source: string;
}

/** Abstract contract for a payment processor implementation */
export interface IPaymentProcessor {
  /**
   * Process a payment request and return a response.
   * Implementations may delegate to specific providers.
   */
  process(request: PaymentRequest): Promise<PaymentResponse>;
}
